spring.application.name=backend

# Perfil por defecto: local
spring.profiles.active=local

# Puerto local (en Render se usa PORT, configurado en application-prod.properties)
server.port=8080

logging.level.org.springframework.web=DEBUG
